# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Build
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
    - name: Download releaseartifacts
      uses: actions/download-artifact@v2
      with:
        name: release-artifacts
        path: release
    - name: Generate checksum
      uses: jmgilman/actions-generate-checksum@v1
      with:
        output: sha256sums.txt
        patterns: |
          release/*.zip
          release/*.tar.gz
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sha256sums.txt
          release/*.zip
          release/*.tar.gz
